version: '3'
services:
  main:
    image: opuscapita/react-menus:dev
    build: .
    depends_on:
     - mysql
     - consul
     - registrator
     - acl
     - user
    labels:
     SERVICE_NAME: 'menus'
     SERVICE_TAGS: 'external,kong'
    environment:
     SERVICE_3000_CHECK_HTTP: /api/health/check
     SERVICE_3000_CHECK_INTERVAL: 15s
     SERVICE_3000_CHECK_TIMEOUT: 3s
     MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
     MYSQL_DATABASE: ${MYSQL_DATABASE}
    ports:
     - '3000:3000'

  mysql:
    image: "mysql:5.7"
    ports:
     - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
    depends_on:
     - registrator

  nginx-rp:
    image: opuscapita/nginx-rp:dev
    ports:
      - '8080:8080'
    depends_on:
      - registrator

  registrator:
    image: gliderlabs/registrator
    command: consul://consul:8500
    volumes:
      - /var/run/docker.sock:/tmp/docker.sock
    depends_on:
      - consul

  consul:
    image: consul:latest
    ports:
      - '8400:8400'
      - '8500:8500'
      - '8600:53/udp'
    labels:
      SERVICE_IGNORE: 'true'  # Do not add any of Consul's services to Consul's service discovery registry.
    command: [agent, '-server', '-ui', '-bootstrap', '-client=0.0.0.0']

  redis:
    image: 'opuscapita/redis:dev'
    environment:
      REDIS_AUTH: ${REDIS_AUTH}
    depends_on:
      - registrator
    ports:
      - ${REDIS_PORT}:${REDIS_PORT}

  acl:
    image: opuscapita/acl:dev
    labels:
      SERVICE_NAME: 'acl'
      SERVICE_TAGS: 'external,kong'
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      SERVICE_3013_CHECK_HTTP: /api/health/check
      SERVICE_3013_CHECK_INTERVAL: 15s
      SERVICE_3013_CHECK_TIMEOUT: 3s
    ports:
     - '3013:3013'
    depends_on:
      - consul
    command: 'npm run dev'

  user:
    image: opuscapita/user:dev
    depends_on:
      - mysql
      - consul
      - registrator
    labels:
      SERVICE_NAME: 'user'
      SERVICE_TAGS: 'external,kong'
    environment:
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      REDIS_AUTH: ${REDIS_AUTH}
      USER_NAME: 'svc_user'
      PASSWORD: 'test'
      CLIENT_KEY: ${CLIENT_KEY}
      CLIENT_SECRET: ${CLIENT_SECRET}
      SERVICE_3008_CHECK_HTTP: /api/health/check
      SERVICE_3008_CHECK_INTERVAL: 15s
      SERVICE_3008_CHECK_TIMEOUT: 3s
    ports:
      - '3008:3008'
    command: 'npm run dev'
